### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by Goosia** [minsuk-heo/machinelearning#1]
Python 버전 : 3.7.4

Error log : 
Traceback (most recent call last):  File "c:/Dev/python/kNN.py", line 59, in <module>
    result = classify0([2.0, 3.0], group, labels,3)
  File "c:/Dev/python/kNN.py", line 53, in classify0
    sortedClassCount = findMajorityClass(inX, dataSet, labels, k, sortedDistIndices)
  File "c:/Dev/python/kNN.py", line 46, in findMajorityClass
    return sorted(classCount.iteritems(), key=operator.itemgetter(1), reverse=True)
AttributeError: 'dict' object has no attribute 'iteritems'

Solve:
Line 46 = return sorted(classCount.iteritems(), key=operator.itemgetter(1), reverse=True)
iteritems => items 로 수정

**Comment by Goosia** [comment]
아...혹시..몰라서 60번줄에 print result 는 print(result) 임.
